"""initial schema

Revision ID: d2cd1a2a2b76
Revises: 
Create Date: 2026-03-11 21:00:04.694895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd2cd1a2a2b76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('revenue_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_uploads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provided_data', sqlite.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_uploads_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_data_uploads_company_year', ['company_id', 'year'], unique=False)

    op.create_table('questionnaires',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionnaires_company_id'), ['company_id'], unique=False)

    op.create_table('supply_chain_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('buyer_company_id', sa.String(length=32), nullable=False),
    sa.Column('supplier_company_id', sa.String(length=32), nullable=False),
    sa.Column('spend_usd', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['supplier_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_company_id', 'supplier_company_id', name='uq_supply_chain_buyer_supplier')
    )
    with op.batch_alter_table('supply_chain_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_chain_links_buyer_company_id'), ['buyer_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_chain_links_supplier_company_id'), ['supplier_company_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('webhooks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('event_types', sqlite.JSON(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_company_id'), ['company_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('emission_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('data_upload_id', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('scope1', sa.Float(), nullable=False),
    sa.Column('scope2', sa.Float(), nullable=False),
    sa.Column('scope3', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('breakdown', sqlite.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sources', sqlite.JSON(), nullable=True),
    sa.Column('assumptions', sqlite.JSON(), nullable=True),
    sa.Column('methodology_version', sa.String(length=50), nullable=True),
    sa.Column('miner_scores', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['data_upload_id'], ['data_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emission_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emission_reports_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_emission_reports_company_year', ['company_id', 'year'], unique=False)

    op.create_table('questionnaire_questions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('questionnaire_id', sa.String(length=32), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('ai_draft_answer', sa.Text(), nullable=True),
    sa.Column('human_answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questionnaire_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionnaire_questions_questionnaire_id'), ['questionnaire_id'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('webhook_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_webhook_id'), ['webhook_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_report_id', sa.String(length=32), nullable=True),
    sa.Column('parameters', sqlite.JSON(), nullable=False),
    sa.Column('results', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['base_report_id'], ['emission_reports.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_company_id'))

    op.drop_table('scenarios')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_webhook_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('questionnaire_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionnaire_questions_questionnaire_id'))

    op.drop_table('questionnaire_questions')
    with op.batch_alter_table('emission_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_emission_reports_company_year')
        batch_op.drop_index(batch_op.f('ix_emission_reports_company_id'))

    op.drop_table('emission_reports')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_company_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_company_id'))

    op.drop_table('webhooks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('supply_chain_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_chain_links_supplier_company_id'))
        batch_op.drop_index(batch_op.f('ix_supply_chain_links_buyer_company_id'))

    op.drop_table('supply_chain_links')
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionnaires_company_id'))

    op.drop_table('questionnaires')
    with op.batch_alter_table('data_uploads', schema=None) as batch_op:
        batch_op.drop_index('ix_data_uploads_company_year')
        batch_op.drop_index(batch_op.f('ix_data_uploads_company_id'))

    op.drop_table('data_uploads')
    op.drop_table('companies')
    # ### end Alembic commands ###
